main: smp.edgecraft.uhc.core.UHCCore
name: UHCCore
version: 0.0.0.1
author: CJMinecraft
description: The core gameplay for a UHC
api-version: 1.13
commands:
  uhc:
    description: The main command for the UHC
    usage: /uhc